steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", ".", "gs://www.epstein.consulting"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rm", "-rf", "gs://www.epstein.consulting/.git", "gs://www.epstein.consulting/.gitignore"]

